site_name: libspng v0.7.0
site_url: https://libspng.org/docs
repo_url: https://github.com/randy408/libspng/
site_description: libspng documentation
site_author: Randy
copyright: Â© 2018-2021, Randy

nav:
    - 'libspng documentation': 'index.md'
    - 'Build': 'build.md'
    - 'API Documentation': 'api.md'
    - 'Usage': 'usage.md'

theme:
    name: material
    palette:
        primary: indigo
        accent: indigo

site_dir: 'site'

markdown_extensions:
    - smarty
    - fenced_code
    - admonition
    - codehilite
    - markdown.extensions.toc:
        permalink: true

plugins:
    - search
